name = "AphrodisiacProblem"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["AphrodisiacProblem"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.8.0"

[[lean_lib]]
name = "AphrodisiacProblem"
