name = "PotionProblem"
version = "1.0.0"
keywords = ["mathematics", "probability", "stopping-time", "hitting-time", "exponential"]
defaultTargets = ["UniformHittingTime"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "UniformHittingTime"
srcDir = "lean"